
set nu
set clipboard=unnamed
"设置文件的代码形式 utf8
set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,chinese,cp936

"vim的菜单乱码解决
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

filetype on
filetype plugin indent on
set history=500                "保留历史记录
set guifont=Monaco:h10        "设置字体为Monaco，大小10
set tabstop=4                "设置tab的跳数
set expandtab
set backspace=2         "设置退格键可用
"set nu!                 "设置显示行号
set wrap                 "设置自动换行
"set nowrap                 "设置不自动换行
set linebreak                 "整词换行，与自动换行搭配使用
"set list                 "显示制表符
set autochdir                 "自动设置当前目录为正在编辑的目录
set scrolloff=5         "在光标接近底端或顶端时，自动下滚或上滚
"set guioptions-=m
"set guioptions-=T
set showtabline=2         "设置显是显示标签栏
set autoread                 "设置当文件在外部被修改，自动更新该文件
set mouse=a                 "设置在任何模式下鼠标都可用
set nobackup                 "设置不生成备份文件
"set go=                                "不要图形按钮
